/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpreadsImport } from './routes/spreads'
import { Route as FormulaeImport } from './routes/formulae'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SpreadsRoute = SpreadsImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => rootRoute,
} as any)

const FormulaeRoute = FormulaeImport.update({
  id: '/formulae',
  path: '/formulae',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/formulae': {
      id: '/formulae'
      path: '/formulae'
      fullPath: '/formulae'
      preLoaderRoute: typeof FormulaeImport
      parentRoute: typeof rootRoute
    }
    '/spreads': {
      id: '/spreads'
      path: '/spreads'
      fullPath: '/spreads'
      preLoaderRoute: typeof SpreadsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formulae': typeof FormulaeRoute
  '/spreads': typeof SpreadsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formulae': typeof FormulaeRoute
  '/spreads': typeof SpreadsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/formulae': typeof FormulaeRoute
  '/spreads': typeof SpreadsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/formulae' | '/spreads'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formulae' | '/spreads'
  id: '__root__' | '/' | '/formulae' | '/spreads'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormulaeRoute: typeof FormulaeRoute
  SpreadsRoute: typeof SpreadsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormulaeRoute: FormulaeRoute,
  SpreadsRoute: SpreadsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/formulae",
        "/spreads"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/formulae": {
      "filePath": "formulae.tsx"
    },
    "/spreads": {
      "filePath": "spreads.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
