/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpreadsImport } from './routes/spreads'
import { Route as IndexImport } from './routes/index'
import { Route as FormulaeIndexImport } from './routes/formulae/index'
import { Route as FormulaeFormulaIdImport } from './routes/formulae/$formulaId'

// Create/Update Routes

const SpreadsRoute = SpreadsImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormulaeIndexRoute = FormulaeIndexImport.update({
  id: '/formulae/',
  path: '/formulae/',
  getParentRoute: () => rootRoute,
} as any)

const FormulaeFormulaIdRoute = FormulaeFormulaIdImport.update({
  id: '/formulae/$formulaId',
  path: '/formulae/$formulaId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/spreads': {
      id: '/spreads'
      path: '/spreads'
      fullPath: '/spreads'
      preLoaderRoute: typeof SpreadsImport
      parentRoute: typeof rootRoute
    }
    '/formulae/$formulaId': {
      id: '/formulae/$formulaId'
      path: '/formulae/$formulaId'
      fullPath: '/formulae/$formulaId'
      preLoaderRoute: typeof FormulaeFormulaIdImport
      parentRoute: typeof rootRoute
    }
    '/formulae/': {
      id: '/formulae/'
      path: '/formulae'
      fullPath: '/formulae'
      preLoaderRoute: typeof FormulaeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spreads': typeof SpreadsRoute
  '/formulae/$formulaId': typeof FormulaeFormulaIdRoute
  '/formulae': typeof FormulaeIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spreads': typeof SpreadsRoute
  '/formulae/$formulaId': typeof FormulaeFormulaIdRoute
  '/formulae': typeof FormulaeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/spreads': typeof SpreadsRoute
  '/formulae/$formulaId': typeof FormulaeFormulaIdRoute
  '/formulae/': typeof FormulaeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spreads' | '/formulae/$formulaId' | '/formulae'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spreads' | '/formulae/$formulaId' | '/formulae'
  id: '__root__' | '/' | '/spreads' | '/formulae/$formulaId' | '/formulae/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpreadsRoute: typeof SpreadsRoute
  FormulaeFormulaIdRoute: typeof FormulaeFormulaIdRoute
  FormulaeIndexRoute: typeof FormulaeIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpreadsRoute: SpreadsRoute,
  FormulaeFormulaIdRoute: FormulaeFormulaIdRoute,
  FormulaeIndexRoute: FormulaeIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/spreads",
        "/formulae/$formulaId",
        "/formulae/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/spreads": {
      "filePath": "spreads.tsx"
    },
    "/formulae/$formulaId": {
      "filePath": "formulae/$formulaId.tsx"
    },
    "/formulae/": {
      "filePath": "formulae/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
