/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SpreadsImport } from './routes/spreads'
import { Route as IndexImport } from './routes/index'
import { Route as FormulaIndexImport } from './routes/formula/index'

// Create/Update Routes

const SpreadsRoute = SpreadsImport.update({
  id: '/spreads',
  path: '/spreads',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormulaIndexRoute = FormulaIndexImport.update({
  id: '/formula/',
  path: '/formula/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/spreads': {
      id: '/spreads'
      path: '/spreads'
      fullPath: '/spreads'
      preLoaderRoute: typeof SpreadsImport
      parentRoute: typeof rootRoute
    }
    '/formula/': {
      id: '/formula/'
      path: '/formula'
      fullPath: '/formula'
      preLoaderRoute: typeof FormulaIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spreads': typeof SpreadsRoute
  '/formula': typeof FormulaIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spreads': typeof SpreadsRoute
  '/formula': typeof FormulaIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/spreads': typeof SpreadsRoute
  '/formula/': typeof FormulaIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spreads' | '/formula'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spreads' | '/formula'
  id: '__root__' | '/' | '/spreads' | '/formula/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpreadsRoute: typeof SpreadsRoute
  FormulaIndexRoute: typeof FormulaIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpreadsRoute: SpreadsRoute,
  FormulaIndexRoute: FormulaIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/spreads",
        "/formula/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/spreads": {
      "filePath": "spreads.tsx"
    },
    "/formula/": {
      "filePath": "formula/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
